spring:
  application:
    name: auth-service
  cloud:
    nacos:
      username: ${NACOS_USERNAME:} # TODO: 启用 Nacos 认证时由环境变量注入
      password: ${NACOS_PASSWORD:} # TODO: 启用 Nacos 认证时由环境变量注入
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848} # TODO: Nacos 地址
        namespace: ${NACOS_NAMESPACE:local} # TODO: namespace ID
        group: ${NACOS_GROUP:DEFAULT_GROUP} # TODO: 服务分组
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848} # TODO: Nacos 配置中心地址
        namespace: ${NACOS_NAMESPACE:local} # TODO: 配置 namespace ID
        group: ${NACOS_GROUP:DEFAULT_GROUP} # TODO: 配置分组
  config:
    import: optional:nacos:${spring.application.name}.yaml?group=${NACOS_GROUP:DEFAULT_GROUP}&refreshEnabled=true
