<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.hengxue</groupId>
        <artifactId>hengxue-backend</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>
    <artifactId>hengxue-common</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>common-core</module>
        <module>common-web</module>
        <module>common-observability</module>
    </modules>
</project>
